;
;
; far2l (Unix): far2l open with connect
;
Title=far2l
Command=far2l "net::<$$FAR2LCONNECT>"
appliesto=far2l
Description=far2l open use connect info.
KeyFile=/usr/bin/far2l
Platform=unix
ServerType=postgresql
Database=No
SetPassword=No
