;
; Putty (Windows):
;
Title=Putty Console
Command="C:\Program Files\PuTTY\putty.exe" postgres@"$$HOSTNAME"
Description=Open a Putty console to the current database hostname.
KeyFile=C:\Program Files\PuTTY\putty.exe
Platform=windows
ServerType=postgresql
Database=No
SetPassword=No
;
; Putty (Windows): tunnel putty forward
;
Title=[Putty tunnel forward]
Command="C:\Program Files\PuTTY\putty.exe" -load "$$TITLE"
appliesto=puttyforward
Description=Putty forward tunnel from local port.
KeyFile=C:\Program Files\PuTTY\putty.exe
Platform=windows
ServerType=postgresql
Database=No
SetPassword=No
;
; putty (Unix):
;
Title=Putty
Command=putty postgres@"$$HOSTNAME"
Description=Open a Putty console to the current database hostname.
KeyFile=/usr/bin/putty
Platform=unix
ServerType=postgresql
Database=No
SetPassword=No
;
;
; putty (Unix): tunnel putty forward
;
Title=[Putty tunnel forward]
Command=putty -load "$$TITLE"
appliesto=puttyforward
Description=Putty forward tunnel from local port.
KeyFile=/usr/bin/putty
Platform=unix
ServerType=postgresql
Database=No
SetPassword=No
