;
; SSH tun 22333 (Unix):
;
Title=SSH Tunnel port 22333
Command=/usr/bin/pterm -T "server=$$DESCRIPTION tunnel $$PORT" -e "/home/sergey/script/tunnel22333.bash" "$$DESCRIPTION" $$PORT
Description=Открытие туннеля на порт 22333 использую название сервера(db_name).
KeyFile=/home/sergey/script/tunnel22333.bash
Platform=unix
ServerType=postgresql
Database=No
SetPassword=No
